apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pf-dashboard
  namespace: pf-dashboard
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  rules:
    - host: pf-dashboard.local
      http:
        paths:
          # UI 경로
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pf-dashboard-ui
                port:
                  number: 80
          # API 경로
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: pf-dashboard-api
                port:
                  number: 8080
