apiVersion: v1
kind: Service
metadata:
  name: pf-dashboard-ui-nodeport
  namespace: pf-dashboard
  labels:
    app: pf-dashboard-ui
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP
      name: http
  selector:
    app: pf-dashboard-ui
---
apiVersion: v1
kind: Service
metadata:
  name: pf-dashboard-api-nodeport
  namespace: pf-dashboard
  labels:
    app: pf-dashboard-api
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30088
      protocol: TCP
      name: http
  selector:
    app: pf-dashboard-api
